name: Soundboard

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku git:remote --app chime-soundboard
          git config --global user.name MaxHalford
          git config --global user.email maxhalford25@gmail.com
          git subtree push --prefix soundboard heroku main
