name: tests

on: [push]

jobs:
  ubuntu:

    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install aplay
      run: sudo apt-get install alsa-utils pulseaudio
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: pytest
      run: |
        pytest

  other:

    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: pytest
      run: |
        pytest
