name: tests

on: [push]

jobs:
  build:

    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ubuntu-latest
    steps:
    - name: Install aplay
      run: apt-get install alsa-utils

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: pytest
      run: |
        pytest
